Another attempt at logging

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,6 +3,7 @@
 set -e
 
 echo "-----> CHECKING /usr/lib"
-ls /usr/lib | grep libxmlsec1
+ls /usr/lib | grep libxmlsec1 || echo "libxmlsec1 not found in /usr/lib"
+
 echo "-----> CHECKING /usr/local/lib"
-ls /usr/local/lib | grep libxmlsec1
+ls /usr/local/lib | grep libxmlsec1 || echo "libxmlsec1 not found in /usr/local/lib"
